package common;

public enum HotelSortType {
	MULTIPLE_HIGH_TO_LOW,//综合排序
	MULTIPLE_LOW_TO_HIGH,
	PRICE_HIGH_TO_LOW,
	PRICE_LOW_TO_HIGH,
	STARLEVEL_HIGH_TO_LOW,
	STARLEVEL_LOW_TO_HIGH,
	SCORE_HIGH_TO_LOW,
	SCORE_LOW_TO_HIGH,
}
